### ISSUE TITLE
Implement Profile settings page Design

### ISSUE THREAD

**Issue by musayann** [dacadeorg/dacade-webapp#248]
https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?node-id=13229%3A15441&t=s9FMMaiHIuQIoyst-0

**Comment by nathaniawong** [comment]
@musayann to review by Tuesday, 16 May.

**Comment by nathaniawong** [comment]
@musayann to review by Monday, 22 May.

**Comment by nathaniawong** [comment]
@gabrielaacha to resolve comments by Monday, 22 May.

**Comment by nathaniawong** [comment]
@gabrielaacha will finish today for @musayann to review

**Comment by nathaniawong** [comment]
@gabrielaacha will finish today for @musayann to review

**Comment by nathaniawong** [comment]
@musayann to review by Monday, 29 May.

**Comment by nathaniawong** [comment]
@musayann to review by Friday, 2 June.

**Comment by nathaniawong** [comment]
@musayann: @gabrielaacha is currently moving that into the React version. I had already reviewed the version in vue js.
