### ISSUE TITLE
Implement verification badge and the verify button

### ISSUE THREAD

**Issue by moritzfelipe** [dacadeorg/dacade-webapp#249]
Badge
https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?node-id=13429%3A13474&t=s9FMMaiHIuQIoyst-0

Button
https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?node-id=13797%3A22458&t=s9FMMaiHIuQIoyst-0

**Comment by moritzfelipe** [comment]
@karemarsy https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?type=design&node-id=15664-23794&t=vPNbxcOOp2HPTVk2-0 this should be the one

**Comment by nathaniawong** [comment]
@karemarsy will work on it by Monday, 22 May.

**Comment by nathaniawong** [comment]
@musayann merged.
