### ISSUE TITLE
Implement Profile settings page Functionality

### ISSUE THREAD

**Issue by moritzfelipe** [dacadeorg/dacade-webapp#255]
https://www.figma.com/file/6Hq5cBH6doeIrspVLzDyQt/Dacade?node-id=13229%3A15441&t=s9FMMaiHIuQIoyst-0

**Comment by nathaniawong** [comment]
@musayann to review by Tuesday, 16 May.

**Comment by nathaniawong** [comment]
@musayann to review by Monday, 22 May.

**Comment by nathaniawong** [comment]
@gabrielaacha to resolve comments by Monday, 22 May.

**Comment by nathaniawong** [comment]
@gabrielaacha will finish today for @musayann to review

**Comment by nathaniawong** [comment]
@gabrielaacha will finish today for @musayann to review

**Comment by nathaniawong** [comment]
@musayann to review by Monday, 29 May.

**Comment by nathaniawong** [comment]
@musayann to review by Friday, 2 June.

**Comment by nathaniawong** [comment]
@gabrielaacha has completed all changes. Waiting on @musayann to confirm and review.
